await import('./apiCnpj.js')
await import('./apiNire.js')
await import('./awaitLoad.js')
await import('./button.js')
await import('./checkPage.js')
await import('./cookiesGetSet.js')
await import('./getTextElement.js')
await import('./imput.js')
await import('./navigate.js')
await import('./sendData.js')

